# Generated by Django 5.2 on 2025-05-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user_name',
            new_name='user',
        ),
    ]
